// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLzoSd9vNF2dCtz2kparyN8xG1cU9ryk',
    appId: '1:112241173585:web:b254294d84169634c2c470',
    messagingSenderId: '112241173585',
    projectId: 'drapple-35762',
    authDomain: 'drapple-35762.firebaseapp.com',
    storageBucket: 'drapple-35762.firebasestorage.app',
    measurementId: 'G-GPYPMXJK8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGIzFblQE_78kiiqGC_nQOzGu2Ha60zlY',
    appId: '1:112241173585:android:1008880b33bdf950c2c470',
    messagingSenderId: '112241173585',
    projectId: 'drapple-35762',
    storageBucket: 'drapple-35762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7IduExWWNjBG8sBeHc48W_UIU-ZNfQLQ',
    appId: '1:137986521543:ios:ffabd2b64ebd5a508f41e2',
    messagingSenderId: '137986521543',
    projectId: 'drapple-c97e0',
    storageBucket: 'drapple-c97e0.firebasestorage.app',
    iosBundleId: 'com.example.drApple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2qHe5UBMo4VzWfL8j7dK80irUen7TX6s',
    appId: '1:112241173585:ios:6bc0c5a03c0aafaac2c470',
    messagingSenderId: '112241173585',
    projectId: 'drapple-35762',
    storageBucket: 'drapple-35762.firebasestorage.app',
    iosBundleId: 'com.example.drApple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHLzoSd9vNF2dCtz2kparyN8xG1cU9ryk',
    appId: '1:112241173585:web:06a19439bf633887c2c470',
    messagingSenderId: '112241173585',
    projectId: 'drapple-35762',
    authDomain: 'drapple-35762.firebaseapp.com',
    storageBucket: 'drapple-35762.firebasestorage.app',
    measurementId: 'G-QZ58QF7XXD',
  );
}