// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1SuJstztaJ5MD6EVuvx1VvvjiGzsMM64',
    appId: '1:115430402325:web:807431bbf19d44c310611c',
    messagingSenderId: '115430402325',
    projectId: 'drapple-lol52',
    authDomain: 'drapple-lol52.firebaseapp.com',
    storageBucket: 'drapple-lol52.firebasestorage.app',
    measurementId: 'G-5YHR0CMVCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB89o938hURn-wf_frTPkMR7mwFDEDas9w',
    appId: '1:115430402325:android:03ab8581496d3bd310611c',
    messagingSenderId: '115430402325',
    projectId: 'drapple-lol52',
    storageBucket: 'drapple-lol52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nJVTGqKvJyRHphSAU9cNguDZhcwBgFU',
    appId: '1:115430402325:ios:9947283da1009fbc10611c',
    messagingSenderId: '115430402325',
    projectId: 'drapple-lol52',
    storageBucket: 'drapple-lol52.firebasestorage.app',
    iosBundleId: 'com.example.drApple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9nJVTGqKvJyRHphSAU9cNguDZhcwBgFU',
    appId: '1:115430402325:ios:9947283da1009fbc10611c',
    messagingSenderId: '115430402325',
    projectId: 'drapple-lol52',
    storageBucket: 'drapple-lol52.firebasestorage.app',
    iosBundleId: 'com.example.drApple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1SuJstztaJ5MD6EVuvx1VvvjiGzsMM64',
    appId: '1:115430402325:web:7484a2c9fb5040d210611c',
    messagingSenderId: '115430402325',
    projectId: 'drapple-lol52',
    authDomain: 'drapple-lol52.firebaseapp.com',
    storageBucket: 'drapple-lol52.firebasestorage.app',
    measurementId: 'G-3JCXWQQ1T7',
  );

}